### ISSUE TITLE
Retrieve historical inquiries for a user (scoped under me)

### ISSUE THREAD

**Issue by mzikherman** [artsy/metaphysics#549] opened 2017-02-14 18:33 UTC
For https://github.com/artsy/collector-experience/issues/86#issuecomment-278797200 (inquiry section), we need to be able to retrieve a list of inquiries for 'me'.

**Comment by alloy** [comment] 2017-02-14 19:16
Should probably do this as a Relay connection, see e.g. #544

**Comment by alloy** [comment] 2017-02-21 14:40
We want to list _all_ inquiries that a collector has made (i.e. including for works that are now marked as unpublished, deleted, etc).

**Comment by 1aurabrown** [comment] 2017-02-21 14:59
i don't want to include fields that are meant to be internal only, but i supposed these would not be returned from gravity in the first place if they should not be public

**Comment by 1aurabrown** [comment] 2017-02-21 14:59
![screen shot 2017-02-21 at 3 58 09 pm](https://cloud.githubusercontent.com/assets/3171662/23170231/c5546452-f84e-11e6-9b23-c7340bd1d55a.png)

**Comment by alloy** [comment] 2017-02-21 15:37
I think we only need to really expose:

* `inquireable` the embedded artwork
* A boolean field that derives from `status` and `user_reported_outcome` whether or not the inquiry is reported to be sold (by either Artsy or the collector themselves).

**Comment by alloy** [comment] 2017-02-21 17:27
After our sprint planning, it appears that we don’t need to include _any_ status information for now. Correct me if I’m wrong.

**Comment by 1aurabrown** [comment] 2017-02-22 14:59
@alloy ok, then will be only be fetching inquiries which have not been confirmed purchased by stas/some status entry? are we or are we not fetching works that are self-reported as purchased but not confirmed by stas in the same manner? only works with no self-reported purchase and no confirmed purchase status?

**Comment by alloy** [comment] 2017-02-22 17:12
As discussed offline, we only need to be concerned with fetching _all_ of a user’s inquiries and really only return their embedded artworks.

**Comment by 1aurabrown** [comment] 2017-02-23 14:20
So, we need to be able to get the total count of expected results. This is available in a header from gravity. metaphysics currently doesn't pass header data in the promise resolution: https://github.com/artsy/metaphysics/blob/master/lib/loaders/authenticated_http.js#L11-L12

We could make some alternative method that resolves with both headers and body, but then we'd also have to think about how to cache things with that different structure. It seems like in the long run it'd be nice to have headers available in `gravity` `then` functions, but it would require some thinking about how to do that throughout the app since it happens at a level that affects every request. Is there some method that I don't know of to access headers in the function passed to `then` after a `gravity` call?

We could change the gravity response to return the count in the body of the request instead of the headers. but this would require other clients updating to accommodate a new data structure in the body of the response.

**Comment by alloy** [comment] 2017-02-23 14:42
You could probably just pass headers as the second param of the `Gravity` function without breaking compatibility with other existing code.

**Comment by alloy** [comment] 2017-02-23 14:43
(Err, I meant the promise returned from the function.)

**Comment by 1aurabrown** [comment] 2017-02-23 16:44
@alloy the resolve value must be one object--we can't do `resolve(body, header)`. I could do `resolve({body: body, header: header})` however then the way we implement `then`s that are chained to this gravity promise would have to be handled differently. they are currently expection the value to represent the body itself, ie `gravity(......).then(body) => #`. They would then have to accept an _object_ who has keys called body and header, ie `gravity(....)then({ body, header}) => #` which would require changing every `then` chained to a gravity promise. does that make sense? not sure what to do, perhaps there is another way that i'm missing.

**Comment by alloy** [comment] 2017-02-23 17:39
Right right, I see now. As we discussed offline, let’s go with a separate `gravityWithHeaders` function for now and discuss from there on.

**Comment by mzikherman** [comment] 2017-02-23 19:33
I'm 👍  for `gravityWithHeaders` that will pass `{body: body, headers: headers}`, but why not make the update to `gravity`? It requires changing a lot of places in the code but that shouldn't be too hard with a grep, plus we have specs (and can be on the lookout for NewRelic/errors).

**Comment by mzikherman** [comment] 2017-02-23 20:33
Another idea (maybe this isn't such a great one), is to resolve with the body (as we do currently), but just inject the total count into the body? I guess that's more of a band-aid since it doesn't actually leave headers accessible, and also runs the risk of overwriting something with that same name in the API response.

I'm 👍  for `gravityWithHeaders` in that case, or even the global `gravity` update to expose both body and headers.

**Comment by alloy** [comment] 2017-02-23 22:48
I’m ok with replacing it all now or going with `gravityWithHeaders` for now, because I’ll soon go through these loaders anyways (to fix their use according to the DataLoader pattern) which is when I could also consolidate this.

**Comment by 1aurabrown** [comment] 2017-02-28 14:50
closed by https://github.com/artsy/metaphysics/pull/553

**Closed by 1aurabrown** 2017-02-28 14:50 UTC
Labels: Collector Experience
